Engine: engine::ContextBuilder Class Reference
engine::ContextBuilder Class Reference
#include <E:/Programing/Projects/EngineWorkspace/CommonLibs/engine/include/engine/environmentBuilder/ContextBuilder.h>
Public Member Functions
ContextBuilder (const std::vector< ContextModuleType > &moduls)
ContextBuilder (ContextBuilder &&o)
~ContextBuilder ()
ApplicationBuilder buildForApplication ()
Protected Member Functions
void addModule (const ContextModuleType value)
void setApplication (std::unique_ptr< Application > app)
void setWindowManager (std::unique_ptr< WindowManager > manager)
void setEventManager (std::unique_ptr< EventManager > manager)
void setInitialized ()
Detailed Description
Creates the context which is the cornerstone of the environment
Definition at line 16 of file ContextBuilder.h.
Constructor & Destructor Documentation
engine::ContextBuilder::ContextBuilder (const std::vector< ContextModuleType > & moduls)
Create the context. This build phase will also initialize the different kind of modules.
Parameters
moduls Modules which will be initialized during the build.
engine::ContextBuilder::ContextBuilder (ContextBuilder && o)
Moveable
engine::ContextBuilder::~ContextBuilder ()
Destructor for PIMPL
Member Function Documentation
void engine::BaseBuilder::addModule (const ContextModuleType value) protected inherited
Add a module type which is initialized during build phase
Parameters
value Module which is initialized successfully
Referenced by engine::BaseBuilder::~BaseBuilder().
ApplicationBuilder engine::ContextBuilder::buildForApplication ()
Build the context and init the next step.
Returns
Returns the next building phase.
void engine::BaseBuilder::setApplication (std::unique_ptr< Application > app) protected inherited
Set the context application.
Parameters
app Application to use
Referenced by engine::BaseBuilder::~BaseBuilder().
void engine::BaseBuilder::setEventManager (std::unique_ptr< EventManager > manager) protected inherited
Set the event manager of the context.
Parameters
manager window manager to use
Referenced by engine::BaseBuilder::~BaseBuilder().
void engine::BaseBuilder::setInitialized () protected inherited
When the environment is built up this function finalize the context.
Referenced by engine::BaseBuilder::~BaseBuilder().
void engine::BaseBuilder::setWindowManager (std::unique_ptr< WindowManager > manager) protected inherited
Set the window manager of the context.
Parameters
manager window manager to use
Referenced by engine::BaseBuilder::~BaseBuilder().
The documentation for this class was generated from the following file:
E:/Programing/Projects/EngineWorkspace/CommonLibs/engine/include/engine/environmentBuilder/ContextBuilder.h