Engine: engine::EventBuilder Class Reference
engine::EventBuilder Class Reference
#include <C:/Projects/myProject/engine-workspace/CommonLibs/engine/include/engine/environmentBuilder/EventBuilder.h>
Public Types
enum BasicInputType { BasicInputType::Mouse, BasicInputType::Keyboard }
Public Member Functions
EventBuilder (EventBuilder &&)
~EventBuilder ()
WindowEnvironmentBuilder build (const std::set< BasicInputType > &basicInputs)
WindowEnvironmentBuilder skip ()
Protected Member Functions
void addModule (const ContextModuleType value)
void setApplication (std::unique_ptr< Application > app)
void setWindowManager (std::unique_ptr< WindowManager > manager)
void setEventManager (std::unique_ptr< EventManager > manager)
void setInitialized ()
Friends
class ApplicationBuilder
Detailed Description
Class for building the event system.
Definition at line 17 of file EventBuilder.h.
Member Enumeration Documentation
BasicInputType
enum engine::EventBuilder::BasicInputType strong
Basic input types of the engine
Enumerator
Mouse
Mouse input
Keyboard
Keyboard input
Definition at line 22 of file EventBuilder.h.
Constructor & Destructor Documentation
EventBuilder()
engine::EventBuilder::EventBuilder (EventBuilder &&)
Move for PIMPL
~EventBuilder()
engine::EventBuilder::~EventBuilder ()
PIMPL
Member Function Documentation
addModule()
void engine::BaseBuilder::addModule (const ContextModuleType value) protected inherited
Add a module type which is initialized during build phase
Parameters
value Module which is initialized successfully
Referenced by engine::BaseBuilder::~BaseBuilder().
build()
WindowEnvironmentBuilder engine::EventBuilder::build (const std::set< BasicInputType > & basicInputs)
Builds the event manager.
Parameters
basicInputs These inputs will be handled from the beginning of the engine initialization.
Returns
Returns the next build step.
setApplication()
void engine::BaseBuilder::setApplication (std::unique_ptr< Application > app) protected inherited
Set the context application.
Parameters
app Application to use
Referenced by engine::BaseBuilder::~BaseBuilder().
setEventManager()
void engine::BaseBuilder::setEventManager (std::unique_ptr< EventManager > manager) protected inherited
Set the event manager of the context.
Parameters
manager window manager to use
Referenced by engine::BaseBuilder::~BaseBuilder().
setInitialized()
void engine::BaseBuilder::setInitialized () protected inherited
When the environment is built up this function finalize the context.
Referenced by engine::BaseBuilder::~BaseBuilder().
setWindowManager()
void engine::BaseBuilder::setWindowManager (std::unique_ptr< WindowManager > manager) protected inherited
Set the window manager of the context.
Parameters
manager window manager to use
Referenced by engine::BaseBuilder::~BaseBuilder().
skip()
WindowEnvironmentBuilder engine::EventBuilder::skip ()
The event system is not necessary for the engine, it can be skipped, but in this case no events are supported.
Returns
Returns the next build step.
The documentation for this class was generated from the following file:
C:/Projects/myProject/engine-workspace/CommonLibs/engine/include/engine/environmentBuilder/EventBuilder.h