Engine: engine::ApplicationBuilder Class Reference
engine::ApplicationBuilder Class Reference
#include <C:/Projects/myProject/engine-workspace/CommonLibs/engine/include/engine/environmentBuilder/ApplicationBuilder.h>
Public Member Functions
ApplicationBuilder (ApplicationBuilder &&o)
EventBuilder build (std::unique_ptr< IApplicationParameter > arguments, std::unique_ptr< IMain > main)
Protected Member Functions
void addModule (const ContextModuleType value)
void setApplication (std::unique_ptr< Application > app)
void setWindowManager (std::unique_ptr< WindowManager > manager)
void setEventManager (std::unique_ptr< EventManager > manager)
void setInitialized ()
Friends
class ContextBuilder
Detailed Description
This is the application building phase. After this build phase the context will have an application
Definition at line 21 of file ApplicationBuilder.h.
Member Function Documentation
addModule()
void engine::BaseBuilder::addModule (const ContextModuleType value) protected inherited
Add a module type which is initialized during build phase
Parameters
value Module which is initialized successfully
Referenced by engine::BaseBuilder::~BaseBuilder().
build()
EventBuilder engine::ApplicationBuilder::build (std::unique_ptr< IApplicationParameter > arguments, std::unique_ptr< IMain > main)
Build an application with the given arguments and main.
Parameters
arguments arguments of the application
main Main functionality.
Returns
The next building phase.
setApplication()
void engine::BaseBuilder::setApplication (std::unique_ptr< Application > app) protected inherited
Set the context application.
Parameters
app Application to use
Referenced by engine::BaseBuilder::~BaseBuilder().
setEventManager()
void engine::BaseBuilder::setEventManager (std::unique_ptr< EventManager > manager) protected inherited
Set the event manager of the context.
Parameters
manager window manager to use
Referenced by engine::BaseBuilder::~BaseBuilder().
setInitialized()
void engine::BaseBuilder::setInitialized () protected inherited
When the environment is built up this function finalize the context.
Referenced by engine::BaseBuilder::~BaseBuilder().
setWindowManager()
void engine::BaseBuilder::setWindowManager (std::unique_ptr< WindowManager > manager) protected inherited
Set the window manager of the context.
Parameters
manager window manager to use
Referenced by engine::BaseBuilder::~BaseBuilder().
The documentation for this class was generated from the following file:
C:/Projects/myProject/engine-workspace/CommonLibs/engine/include/engine/environmentBuilder/ApplicationBuilder.h