Engine: engine::BuildFinalizer Class Reference
engine::BuildFinalizer Class Reference
#include <C:/Projects/myProject/engine-workspace/CommonLibs/engine/include/engine/environmentBuilder/BuildFinalizer.h>
Public Member Functions
BuildFinalizer ()=default
BuildFinalizer (BuildFinalizer &&)
void build ()
Protected Member Functions
void addModule (const ContextModuleType value)
void setApplication (std::unique_ptr< Application > app)
void setWindowManager (std::unique_ptr< WindowManager > manager)
void setEventManager (std::unique_ptr< EventManager > manager)
void setInitialized ()
Detailed Description
Last build step. Ensure that the build process reaches the end of the creation. Without this build phase the context cannot be used.
Definition at line 12 of file BuildFinalizer.h.
Constructor & Destructor Documentation
BuildFinalizer() [1/2]
engine::BuildFinalizer::BuildFinalizer () default
Defualt constructor
BuildFinalizer() [2/2]
engine::BuildFinalizer::BuildFinalizer (BuildFinalizer &&) inline
Moveable
Definition at line 18 of file BuildFinalizer.h.
Member Function Documentation
addModule()
void engine::BaseBuilder::addModule (const ContextModuleType value) protected inherited
Add a module type which is initialized during build phase
Parameters
value Module which is initialized successfully
Referenced by engine::BaseBuilder::~BaseBuilder().
build()
void engine::BuildFinalizer::build ()
Finish building process, no more step left.
Referenced by BuildFinalizer().
setApplication()
void engine::BaseBuilder::setApplication (std::unique_ptr< Application > app) protected inherited
Set the context application.
Parameters
app Application to use
Referenced by engine::BaseBuilder::~BaseBuilder().
setEventManager()
void engine::BaseBuilder::setEventManager (std::unique_ptr< EventManager > manager) protected inherited
Set the event manager of the context.
Parameters
manager window manager to use
Referenced by engine::BaseBuilder::~BaseBuilder().
setInitialized()
void engine::BaseBuilder::setInitialized () protected inherited
When the environment is built up this function finalize the context.
Referenced by engine::BaseBuilder::~BaseBuilder().
setWindowManager()
void engine::BaseBuilder::setWindowManager (std::unique_ptr< WindowManager > manager) protected inherited
Set the window manager of the context.
Parameters
manager window manager to use
Referenced by engine::BaseBuilder::~BaseBuilder().
The documentation for this class was generated from the following file:
C:/Projects/myProject/engine-workspace/CommonLibs/engine/include/engine/environmentBuilder/BuildFinalizer.h