Engine: engine::BaseBuilder Class Reference
engine::BaseBuilder Class Reference
#include <C:/Projects/myProject/engine-workspace/CommonLibs/engine/include/engine/environmentBuilder/BaseBuilder.h>
Protected Member Functions
BaseBuilder ()=default
virtual ~BaseBuilder ()
void addModule (const ContextModuleType value)
void setApplication (std::unique_ptr< Application > app)
void setWindowManager (std::unique_ptr< WindowManager > manager)
void setEventManager (std::unique_ptr< EventManager > manager)
void setInitialized ()
Detailed Description
Base class for builder phases. Only via this class one can set up context parameters.
Definition at line 20 of file BaseBuilder.h.
Constructor & Destructor Documentation
BaseBuilder()
engine::BaseBuilder::BaseBuilder () protected default
Default constructor
~BaseBuilder()
virtual engine::BaseBuilder::~BaseBuilder () inline protected virtual
Default destructor
Definition at line 26 of file BaseBuilder.h.
Member Function Documentation
addModule()
void engine::BaseBuilder::addModule (const ContextModuleType value) protected
Add a module type which is initialized during build phase
Parameters
value Module which is initialized successfully
Referenced by ~BaseBuilder().
setApplication()
void engine::BaseBuilder::setApplication (std::unique_ptr< Application > app) protected
Set the context application.
Parameters
app Application to use
Referenced by ~BaseBuilder().
setEventManager()
void engine::BaseBuilder::setEventManager (std::unique_ptr< EventManager > manager) protected
Set the event manager of the context.
Parameters
manager window manager to use
Referenced by ~BaseBuilder().
setInitialized()
void engine::BaseBuilder::setInitialized () protected
When the environment is built up this function finalize the context.
Referenced by ~BaseBuilder().
setWindowManager()
void engine::BaseBuilder::setWindowManager (std::unique_ptr< WindowManager > manager) protected
Set the window manager of the context.
Parameters
manager window manager to use
Referenced by ~BaseBuilder().
The documentation for this class was generated from the following file:
C:/Projects/myProject/engine-workspace/CommonLibs/engine/include/engine/environmentBuilder/BaseBuilder.h