Engine: engine::IMain Class Reference
engine::IMain Class Reference abstract
#include <C:/Projects/myProject/engine-workspace/CommonLibs/engine/include/engine/app/IMain.h>
Public Member Functions
~IMain ()
virtual void load ()=0
virtual void update ()=0
virtual void render ()=0
Protected Member Functions
IMain ()=default
Detailed Description
Base class for core logic of an application
Definition at line 11 of file IMain.h.
Constructor & Destructor Documentation
IMain()
engine::IMain::IMain () protected default
Simple constructor only for child classes.
~IMain()
engine::IMain::~IMain () inline
Simple destructor
Definition at line 18 of file IMain.h.
Member Function Documentation
load()
virtual void engine::IMain::load () pure virtual
Called once when the application is started
Referenced by ~IMain().
render()
virtual void engine::IMain::render () pure virtual
Called once per each frame to render
Referenced by ~IMain().
update()
virtual void engine::IMain::update () pure virtual
Called once per each frame to update the main
Referenced by ~IMain().
The documentation for this class was generated from the following file:
C:/Projects/myProject/engine-workspace/CommonLibs/engine/include/engine/app/IMain.h