Engine: engine::WindowEnvironmentBuilder Class Reference
engine::WindowEnvironmentBuilder Class Reference
#include <C:/Projects/myProject/engine-workspace/CommonLibs/engine/include/engine/environmentBuilder/WindowEnvironmentBuilder.h>
Public Member Functions
~WindowEnvironmentBuilder ()
WindowEnvironmentBuilder (WindowEnvironmentBuilder &&o)
BuildFinalizer build ()
Protected Member Functions
void addModule (const ContextModuleType value)
void setApplication (std::unique_ptr< Application > app)
void setWindowManager (std::unique_ptr< WindowManager > manager)
void setEventManager (std::unique_ptr< EventManager > manager)
void setInitialized ()
Friends
class engine::EventBuilder
Detailed Description
This buildphase will initialize the window environment.
Definition at line 18 of file WindowEnvironmentBuilder.h.
Constructor & Destructor Documentation
~WindowEnvironmentBuilder()
engine::WindowEnvironmentBuilder::~WindowEnvironmentBuilder ()
Destructor for PIMPL
WindowEnvironmentBuilder()
engine::WindowEnvironmentBuilder::WindowEnvironmentBuilder (WindowEnvironmentBuilder && o)
Moveable
Member Function Documentation
addModule()
void engine::BaseBuilder::addModule (const ContextModuleType value) protected inherited
Add a module type which is initialized during build phase
Parameters
value Module which is initialized successfully
Referenced by engine::BaseBuilder::~BaseBuilder().
build()
BuildFinalizer engine::WindowEnvironmentBuilder::build ()
Builds the window module.
Returns
Returns the next building phase.
setApplication()
void engine::BaseBuilder::setApplication (std::unique_ptr< Application > app) protected inherited
Set the context application.
Parameters
app Application to use
Referenced by engine::BaseBuilder::~BaseBuilder().
setEventManager()
void engine::BaseBuilder::setEventManager (std::unique_ptr< EventManager > manager) protected inherited
Set the event manager of the context.
Parameters
manager window manager to use
Referenced by engine::BaseBuilder::~BaseBuilder().
setInitialized()
void engine::BaseBuilder::setInitialized () protected inherited
When the environment is built up this function finalize the context.
Referenced by engine::BaseBuilder::~BaseBuilder().
setWindowManager()
void engine::BaseBuilder::setWindowManager (std::unique_ptr< WindowManager > manager) protected inherited
Set the window manager of the context.
Parameters
manager window manager to use
Referenced by engine::BaseBuilder::~BaseBuilder().
The documentation for this class was generated from the following file:
C:/Projects/myProject/engine-workspace/CommonLibs/engine/include/engine/environmentBuilder/WindowEnvironmentBuilder.h