Engine: engine::ISignalTask Class Reference
engine::ISignalTask Class Reference abstract
#include <C:/Projects/myProject/engine-workspace/CommonLibs/engine/include/engine/signalSlot/SignalTask.h>
Public Member Functions
virtual ~ISignalTask ()
virtual void operator() ()=0
virtual bool isExpired () const =0
Detailed Description
Task which is created from a slot and a given member
Definition at line 10 of file SignalTask.h.
Constructor & Destructor Documentation
~ISignalTask()
virtual engine::ISignalTask::~ISignalTask () inline virtual
Default destructor
Definition at line 14 of file SignalTask.h.
Member Function Documentation
isExpired()
virtual bool engine::ISignalTask::isExpired () const pure virtual
Expired if the SignalCaller has been destroyed.
Implemented in engine::SignalTask< Args >.
Referenced by engine::SignalTask< Args >::operator()(), and ~ISignalTask().
operator()()
virtual void engine::ISignalTask::operator() () pure virtual
Execute the slot
Implemented in engine::SignalTask< Args >.
Referenced by ~ISignalTask().
The documentation for this class was generated from the following file:
C:/Projects/myProject/engine-workspace/CommonLibs/engine/include/engine/signalSlot/SignalTask.h